global:
    scrape_interval: 5s
    external_labels:
        nginx_monitor: 'nginx-monitor'
        rabbitmq_monitor: 'rabbitmq-monitor'

scrape_configs:
    - job_name: 'nginx-exporter'
      static_configs:
        - targets: ['nginx-exporter:9113']
    - job_name: 'rabbitmq'
      static_configs:
        - targets: ['rabbitmq_exporter:9090']