version: '3.2'

services:
  rabbitmq-service:
    image: hansehe/rabbitmq-mqtt:latest
    hostname: rabbitmq-service
    # ports:
      # - 5671:5671
      # - 5672:5672
      # - 15672:15672
      # - 15673:15673
      # - 15675:15675
      # - 8883:8883
      # - 1883:1883
    environment:
      RABBITMQ_NODENAME: rabbit
    networks:
      - backend_network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

networks:
  backend_network:
    external: true

volumes:
  rabbitmq_data:
    external: true