version: '3.2'

services:
    rabbitmq_exporter:
      image: kbudde/rabbitmq-exporter
      hostname: rabbitmq_exporter
      # ports:
      #   - 9999:9090
      environment:
        RABBIT_URL: http://rabbitmq-service:15672
        RABBIT_USER: amqp
        RABBIT_PASSWORD: amqp
        PUBLISH_PORT: 9090
        OUTPUT_FORMAT: JSON
        LOG_LEVEL: debug
      networks:
        - backend_network

networks:
  backend_network:
    external: true