version: '3.2'

services:
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.2.0
    hostname: nginx-exporter
    command: -nginx.scrape-uri http://nginx_nginx:8080/basic_status
    networks:
      - backend_network
    depends_on:
      - nginx_nginx

networks:
  backend_network:
    external: true