version: '3.2'

services:
  prometheus:
    image: hansehe/prometheus-dev-blog:${VERSION}
    hostname: prometheus
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    networks:
      - backend_network
    # ports:
    #     - 9090:9090

  nodeexporter:
    image: prom/node-exporter:latest
    container_name: nodeexporter
    user: root
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    # expose:
    #   - 9100
    networks:
      - backend_network

networks:
  backend_network:
    external: true